name: 'Delete Gem'
description: 'Delete specific version gem from github package'
branding:
  color: purple
  icon: box
inputs:
  package-name:
    description: >
      Name of the package containing the version to delete.
    required: true
  token:
    description: >
      Token with the necessary scopes to delete package versions.
      If num-old-versions-to-delete is used the token also needs the read packages scope.
      Defaults to github.token scoped to the repo running the action. To delete package versions
      of a package outside the repo the action is running in use a Personal Access Token stored as a secret.
    required: true
    default: ''
  organisation-name:
    description: >
      Name of the Organisation is packages are under organisation
    required: true
    default: ''
  repo-name:
    description: >
      Name of the repo for packages are under organisation
    required: true
    default: ''
outputs:
  id: # id of output
    description: 'id of delete gem package'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - package-name: ${{ inputs.package-name }}
    - ${{ inputs.token }}
    - ${{ inputs.organisation-name }}
    - ${{ inputs.repo-name }}
    - ${{ inputs }}
